DISH_TEMPLATES = {
    "Protein Hub": [
        "Grilled Chicken Power Bowl",
        "Chicken Burrito Bowl",
        "High Protein Paneer Bowl",
        "Egg White Wrap",
        "Chicken Steak Meal",
        "Greek Yogurt Parfait",
        "Protein Oats",
        "Chicken Caesar Salad",
        "Peri Peri Chicken Bowl",
        "Muscle Gain Rice Bowl",
        "Chicken Quinoa Bowl",
        "BBQ Chicken Bowl",
        "Paneer Protein Plate",
        "Turkey Wrap",
        "Avocado Chicken Bowl",
        "Salmon Power Bowl",
        "Lean Beef Bowl",
        "Tofu Protein Bowl",
        "Moong Protein Bowl",
        "Protein Pancakes",
        "Chicken Tikka Bowl",
        "Egg Scramble Bowl",
        "Teriyaki Chicken Bowl",
        "Mexican Chicken Bowl",
        "Grilled Fish Bowl",
        "Paneer Burrito Bowl",
        "Healthy Chicken Pasta",
        "Chicken Broccoli Bowl",
        "Protein Sandwich",
        "Power Omelette",
        "Chicken Lettuce Wrap",
        "Chicken Sweet Potato Bowl",
        "Chicken Spinach Bowl",
        "Protein Smoothie",
        "Power Rice Bowl",
        "Chicken Meal Box",
        "High Protein Khichdi",
        "Chicken Veg Bowl",
        "Protein Upma",
        "Chicken Deluxe Bowl"
    ]
}